---
- name: install_dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - python3-pip
    state: present
    update_cache: yes

- name: add_gpg_key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: add_repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
    update_cache: yes

- name: install_packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present

- name: start_service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: install_docker_compose
  get_url:
    url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'