import React, { createContext, useContext, useState, useEffect } from "react";
const translations = {
  de: {
    dashboard: "Dashboard",
    surveys: "Umfragen",
    analytics: "Analysen",
    organizations: "Organisationen",
    members: "Mitglieder",
    settings: "Einstellungen",
    createSurvey: "Neue Umfrage",
    search: "Suche…",
    overview: "Übersicht",
    responseRate: "Antwortrate",
    activeSurveys: "Aktive Umfragen",
    completionRate: "Abschlussquote",
    engagement: "Engagement-Score",
    recentActivity: "Letzte Aktivitäten",
    topSurveys: "Top-Umfragen",
    responseTrend: "Antworttrend",
    logout: "Abmelden",
    availableSurveys: "Verfügbare Umfragen",
    selectSurveyToParticipate: "Wählen Sie eine Umfrage aus, um teilzunehmen oder Ergebnisse anzuzeigen",
    loadingSurveys: "Lade Umfragen...",
    noSurveysAvailable: "Keine Umfragen verfügbar",
    noSurveysDescription: "Es sind noch keine Umfragen vorhanden.",
    takeSurvey: "An Umfrage teilnehmen",
    viewResults: "Ergebnisse anzeigen",
    responses: "Antworten",
    active: "Aktiv",
    planned: "Geplant",
    closed: "Geschlossen",
    min: "min",
    manageSurveys: "Verwalten Sie Ihre Umfragen und nehmen Sie an aktiven Umfragen teil.",
    filterByStatus: "Nach Status filtern",
    allStatus: "Alle Status",
    noDescription: "Keine Beschreibung verfügbar",
    createdOn: "Erstellt am",
    edit: "Bearbeiten",
    language: "Sprache",
    theme: "Design",
    profile: "Profil",
    organization: "Organisation",
    preferences: "Präferenzen",
    integrations: "Integrationen",
    light: "Hell",
    dark: "Dunkel",
    email: "E-Mail",
    name: "Name",
    organizationName: "Organisationsname",
    timezone: "Zeitzone",
    saveChanges: "Änderungen speichern",
    cancel: "Abbrechen",
    saving: "Speichern...",
    saved: "Gespeichert",
    settingsSaved: "Einstellungen erfolgreich gespeichert!",
    settingsFailed: "Fehler beim Speichern der Einstellungen",
    password: "Passwort",
    currentPassword: "Aktuelles Passwort",
    newPassword: "Neues Passwort",
    confirmPassword: "Passwort bestätigen",
    changePassword: "Passwort ändern",
    passwordChanged: "Passwort erfolgreich geändert!",
    passwordMismatch: "Passwörter stimmen nicht überein",
    notifications: "Benachrichtigungen",
    emailNotifications: "E-Mail-Benachrichtigungen",
    surveyUpdates: "Umfrage-Updates",
    weeklyReports: "Wöchentliche Berichte",
    marketingEmails: "Marketing-E-Mails",
    security: "Sicherheit",
    twoFactor: "Zwei-Faktor-Authentifizierung",
    sessions: "Aktive Sitzungen",
    dataExport: "Datenexport",
    exportData: "Daten exportieren",
    deleteAccount: "Konto löschen",
    deleteAccountWarning: "Diese Aktion kann nicht rückgängig gemacht werden",
    confirmDelete: "Löschen bestätigen",
    connect: "Verbinden",
    disconnect: "Trennen",
    connected: "Verbunden",
    notConnected: "Nicht verbunden",
    general: "Allgemein",
    appearance: "Erscheinungsbild",
    account: "Konto",
    privacy: "Datenschutz",
    unsavedChanges: "Sie haben ungespeicherte Änderungen. Möchten Sie fortfahren?",
  },
  en: {
    dashboard: "Dashboard",
    surveys: "Surveys",
    analytics: "Analytics",
    organizations: "Organizations",
    members: "Members",
    settings: "Settings",
    createSurvey: "Create Survey",
    search: "Search…",
    overview: "Overview",
    responseRate: "Response Rate",
    activeSurveys: "Active Surveys",
    completionRate: "Completion Rate",
    engagement: "Engagement Score",
    recentActivity: "Recent Activity",
    topSurveys: "Top Surveys",
    responseTrend: "Response Trend",
    logout: "Log out",
    availableSurveys: "Available Surveys",
    selectSurveyToParticipate: "Select a survey to participate or view results",
    loadingSurveys: "Loading surveys...",
    noSurveysAvailable: "No surveys available",
    noSurveysDescription: "There are no surveys available yet.",
    takeSurvey: "Take Survey",
    viewResults: "View Results",
    responses: "responses",
    active: "Active",
    planned: "Planned",
    closed: "Closed",
    min: "min",
    manageSurveys: "Manage your surveys and participate in active surveys.",
    filterByStatus: "Filter by status",
    allStatus: "All Status",
    noDescription: "No description available",
    createdOn: "Created on",
    edit: "Edit",
    language: "Language",
    theme: "Theme",
    profile: "Profile",
    organization: "Organization",
    preferences: "Preferences",
    integrations: "Integrations",
    light: "Light",
    dark: "Dark",
    email: "Email",
    name: "Name",
    organizationName: "Organization Name",
    timezone: "Timezone",
    saveChanges: "Save Changes",
    cancel: "Cancel",
    saving: "Saving...",
    saved: "Saved",
    settingsSaved: "Settings saved successfully!",
    settingsFailed: "Failed to save settings",
    password: "Password",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    changePassword: "Change Password",
    passwordChanged: "Password changed successfully!",
    passwordMismatch: "Passwords do not match",
    notifications: "Notifications",
    emailNotifications: "Email Notifications",
    surveyUpdates: "Survey Updates",
    weeklyReports: "Weekly Reports",
    marketingEmails: "Marketing Emails",
    security: "Security",
    twoFactor: "Two-Factor Authentication",
    sessions: "Active Sessions",
    dataExport: "Data Export",
    exportData: "Export Data",
    deleteAccount: "Delete Account",
    deleteAccountWarning: "This action cannot be undone",
    confirmDelete: "Confirm Delete",
    connect: "Connect",
    disconnect: "Disconnect",
    connected: "Connected",
    notConnected: "Not Connected",
    general: "General",
    appearance: "Appearance",
    account: "Account",
    privacy: "Privacy",
    unsavedChanges: "You have unsaved changes. Do you want to continue?",
  },
};
type Language = "de" | "en";
type TranslationKey = keyof typeof translations.de;
interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}
const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined,
);
export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "de";
  });
  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);
  const t = (key: string): string => {
    return translations[language][key as TranslationKey] || key;
  };
  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
};
